### PR TITLE
Small fixes

### PR DESCRIPTION
**Pull request by rootkea**

### CODE REVIEW

**Comment by masatake** [comment]
Thank you for taking your time for reporting this.
Your changes are mostly correct.

I inspected the failure of the test.

The functions taking `tagFile *file` expects `file->err == 0`.
The functions sets `file->err = TagErrnoInvalidArgument` if `file->err != 0`.

This is expected behavior in `tests/test-api-tagsSetSortType.c`.
Your code changes the behavior.

To keep our API, changes are needed on your changes like:
```
diff --git a/readtags.c b/readtags.c
index 942a2c73..0173c841 100644
--- a/readtags.c
+++ b/readtags.c
@@ -1038,10 +1038,10 @@ static tagResult findSequentialFull (tagFile *const file,
 									 int (* isAcceptable) (tagFile *const, void *),
 									 void *data)
 {
-	if (file == NULL || file->err)
+	if (file == NULL)
 		return TagFailure;
 
-	if (!file->initialized)
+	if (!file->initialized || file->err)
 	{
 		file->err = TagErrnoInvalidArgument;
 		return TagFailure;
```

Could you update your change?

You can run the test locally with "make check".

**Comment by rootkea** [comment]
> The functions sets `file->err = TagErrnoInvalidArgument` if `file->err != 0`.

Then aren't we overwriting the `err`? We will be printing `TagErrnoInvalidArgument` instead of the actual original error occurred.

**Comment by masatake** [comment]
> We will be printing TagErrnoInvalidArgument instead of the actual original error occurred.

Overwriting is the expected behavior.

**Comment by masatake** [comment]
Do you have a plan to add more commits to this pull request?
If not, press the "Ready for review" button.

I will merge this. I will add the following entry to NEWS.md file:
```Markdown
- fix potential crashes trigged when passing NULL as `file` parameter
  to the API functions. Provided by Avinash Sonawane.
```

**Comment by rootkea** [comment]
Ready for review!

Please let me know if something needs to be changed/removed. :)

**Comment by rootkea** [comment]
> ```gfm
> Provided by Avinash Sonawane.
> ```

BTW, I'll appreciate if you could make it as `Provided by rootkea`. :)

**Comment by masatake** [comment]
For making understanding the changes from `git log --oneline` easier, could you add prefixes to the header of each commit?

```
buildsys: set executable (+x) permission on autogen.sh
tests: remove redundant argument
tests:  remove redundant code 
tests:  use snprintf() instead of sprintf()
```

This request for adding prefixes is applicable to your pull request sent to `ctags` repository, too.

> BTW, I'll appreciate if you could make it as Provided by rootkea. :)

I see.

**Comment by rootkea** [comment]
> For making understanding the changes from `git log --oneline` easier, could you add prefixes to the header of each commit?

Done!

**Comment by masatake** [comment]
Thank you!

**Comment by masatake** [comment]
Updating NEWS.md is done.

**Comment by masatake** [comment]
The next step of mine is pulling the change into the ctags source tree.
Updating universal-ctags/python-ctags3 is another task.

**Pull request merged**
